language: swift
osx_image: xcode11
script:
 - xcodebuild -scheme npsapi-swift-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
